spring:
  cloud:
    function:
      definition: handleAfterSendMail;
    stream:
      bindings:
        handleAfterSendMail-in-0:
          destination: handleAfterSendMail
          group: users
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/HuyShop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
