
server:
  port: 8100
spring:
  cloud:
    stream:
      bindings:
        purchaseChannel:
          destination: purchases
#  rabbitmq:
#    host: localhost
#    password: guest
#    port: 15672
#    username: guest
#    exchange: purcharse.exchange
#    queue: purcharse.queue
#    routingkey: purcharse.routingkey
  mail:
    host: smtp.gmail.com
    port: '587'
    username: huynhhuy9693@gmail.com
    password: cyvnmufgfyvzqtvw
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: '5000'
          timeout: '5000'
          writetimeout: '5000'
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
