server:
  port: 8084

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'

spring:
  application:
    name: report-service
  main:
    allow-circular-references: true
    output:
      ansi:
        enabled: always

jwt:
  secret: huyhuynh
  get:
    token:
      uri: /authenticate