server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8081/
          predicates:
            - Path=/admin-product/**
        - id: cart
          uri: http://localhost:8083/
          predicates:
            - Path=/cart/**
        - id: user
          uri: http://localhost:8082/
          predicates:
            - Path=/admin-user/**
        - id: report
          uri: http://localhost:8084/
          predicates:
            - Path=/report/**
        - id: mail
          uri: http://localhost:8085/
          predicates:
            - Path=/mail/**
        - id: security
          uri: http://localhost:9999/
          predicates:
            - Path=/security/**

  application:
    name: gateway-service


eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'

keycloak:
  realm: myproject
  auth-server-url: http://localhost:8180
  resource: huyshop
  public-client: true
  bearer-only: true

